name: Deploy MkDocs
on:
  push:
    branches:
      - main
      - dev
      - '*/dev'
      - '*/main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install mkdocs mkdocs-material mkdocs-glightbox mkdocs-to-pdf

      - run: |
          echo "VERSION=$(curl -f https://raw.githubusercontent.com/Security-Onion-Solutions/securityonion/refs/heads/3/dev/VERSION)" >> $GITHUB_ENV 
        shell: bash

      - run: echo "Found version $VERSION"
      
      - run: mkdocs build

      - run: npx -y @redocly/cli build-docs specs/openapi.yaml -o /home/runner/work/docs/docs/site/connect-api/so-api-reference.html

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site                  # mkdocs default output dir
          branch: gh-pages              # your Pages source branch
          token: ${{ steps.generate_token.outputs.token }}
          clean: false                  # IMPORTANT: false prevents wiping other folders
          target-folder: ${{ github.ref_name == 'main' && '.' || format('en/{0}', github.ref_name) }}
